version: '3'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-CU12-ubuntu"
    environment:
      SA_PASSWORD: "Administrator1!"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"